FROM alpine:3.6 AS builder

RUN apk --update add go git musl-dev

RUN mkdir /gclient
COPY main.go /gclient
WORKDIR /gclient
RUN go get -u github.com/go-redis/redis
RUN go build -ldflags="-s -w"

FROM alpine:3.6
COPY --from=builder /gclient/gclient /
CMD ["./gclient"]
