FROM alpine:3.6
MAINTAINER Kenichi Sato <ksato9700@gmail.com>
RUN mkdir /gclient
COPY main.go /gclient
WORKDIR /gclient

RUN apk --update add go git musl-dev && \
    go get -u github.com/go-redis/redis && \
    go build && \
    apk del go git musl-dev && \
    rm -rf ~/go /var/cache/apk/*

CMD ["./gclient"]
